### ISSUE TITLE
A single bad request kills the server

### ISSUE THREAD

**Issue by yschimke** [whyoleg/rkncli#1]
```
route: 
Exception in thread "DefaultDispatcher-worker-1 @coroutine#2" io.rsocket.kotlin.RSocketError$Setup$Rejected: Fail to parse url: 
	at io.rsocket.kotlin.core.RSocketServer.start(RSocketServer.kt:50)
	at io.rsocket.kotlin.core.RSocketServer$bind$1.invokeSuspend(RSocketServer.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:237)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:162)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:372)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:406)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:398)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:303)
	at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKey(SelectorManagerSupport.kt:83)
	at io.ktor.network.selector.SelectorManagerSupport.handleSelectedKeys(SelectorManagerSupport.kt:63)
	at io.ktor.network.selector.ActorSelectorManager.process(ActorSelectorManager.kt:72)
	at io.ktor.network.selector.ActorSelectorManager$process$1.invokeSuspend(ActorSelectorManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

This is from `rsocketcli.exe tcp://localhost:9000`, that is missing the setup frame with a URL.

**Comment by whyoleg** [comment]
Yes, I think that's a bug in rsocket-kotlin with TCP transport. Failing of ANY connection will fail TCP server Job. Better to create a bug in rsocket-kotlin
